version: '3'
services:
  statusok:
    # image: ghcr.io/vemonet/statusok:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./config:/config
    depends_on:
      - influxdb
    networks:
      - network
    ## For debugging:
    # entrypoint: tail -f /dev/null

  influxdb:
    image: tutum/influxdb:0.9
    restart: unless-stopped
    environment:
      - PRE_CREATE_DB="statusok" 
    ports:
      - 8083:8083 
      - 8086:8086
    networks:
      - network

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    # Deploy using jwilder nginx proxy
    # environment:
    # - VIRTUAL_HOST=statusok.137.120.31.101.nip.io 
    # - VIRTUAL_PORT=3000
    networks:
      - network

networks:
  network:
    driver: bridge
