version: '2'
services:
  statusok:
    image: wildsurfer/statusok
    volumes:
      - ./config:/config
    depends_on:
      - influxdb
    networks:
      - network
  influxdb:
    image: tutum/influxdb:0.9
    environment:
      - PRE_CREATE_DB="statusok" 
    ports:
      - 8083:8083 
      - 8086:8086
    networks:
      - network
  grafana:
    image: grafana/grafana
    # Deploy using jwilder nginx proxy
    # environment:
    # - VIRTUAL_HOST=statusok.137.120.31.101.nip.io 
    # - VIRTUAL_PORT=3000
    networks:
      - network

networks:
  network:
    driver: bridge
